services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
