version: '3'

services:
  backend:
    build: 
      context: .
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_LINK=${API_LINK}
      - SECRET_KEY=${SECRET_KEY}
      - NODE_ENV=${NODE_ENV}
      - FRONTEND_URL=${FRONTEND_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge